### ISSUE TITLE
Provide `orc_confirmBlockHashes` for pandora and vanguard

### ISSUE THREAD

**Issue by blazejkrzak** [lukso-network/lukso-orchestrator#12]
Provide `orc_confirmBlockHashes` endpoint for pandora and vanguard.
Proposition is to statuses instead of boolean.
Possible statuses:
- `pending`
- `verified`
- `invalid`

```
3. 🦺 pan > orc : confirmBlockBatch: 'orc_confirmBlockHashes', params: [[{slot: 1, hash: blockHash},...]]
    > [{slot: 1, status: 'pending'}, {slot: 2, 'verified'}, {slot: 3, 'invalid'}, ...]
```

**Comment by blazejkrzak** [comment]
Im on it.

In first iteration it will be just simply returning `true` for each hash, and be used more like a mock to test the connectivity.
Next iteration will provide logic to confirm validity of blocks

**Comment by blazejkrzak** [comment]
https://hackmd.io/@eo9jf8QvQfWAZwf73BXHBg/HJtL6zBtd/edit

**Comment by atif-konasl** [comment]
@blazejkrzak the api will get request of sorted slots and will provide response also in sorted slots

**Comment by atif-konasl** [comment]
Closing this issue. Already merged the feature.
