### ISSUE TITLE
Vanguard client for minimalConsensusInfo via grpc

### ISSUE THREAD

**Issue by blazejkrzak** [lukso-network/lukso-orchestrator#32]
We should move RPC `van_minimalConsensusInfo` into gRPC implementation. To accomplish we must write gRPC client in orchestrator side and use protobufs from correct vanguard-apis repository.

**Comment by atif-konasl** [comment]
@blazejkrzak BTW, [https://github.com/lukso-network/lukso-orchestrator/issues/28](https://github.com/lukso-network/lukso-orchestrator/issues/28) similar issue has been already created before. Okay i am deleting the issue.
