### ISSUE TITLE
Implement block confirmation api for vanguard.

### ISSUE THREAD

**Issue by atif-konasl** [lukso-network/lukso-orchestrator#35]
### Overview 
Need an rpc api for providing consensus status for certain slots and block hash to vanguard client. This is a simple rpc api. 
Api looks like: 
` confirmBlockBatch: 'orc_confirmBlockHashesVan', params: [[{slot: 1, hash: blockHash},...]] > [{slot: 1, status: 'pending'}, {slot: 2, status: 'verified'}, {slot: 3, status: 'unknown'}, ...]`

### Responsibilities
1. When it gets a request from vanguard, it will first search into its db as well into its cache.
2. `Pending` blocks will be existed into its cache and `verified` block hashes will be stored in db. So this api will prepare the status of requested block hashes and slots. If any hash or slot is not existed into cache or db then that block hash status will be `Unknown`
3. Then it returns the batch of the status to the vanguard node.

_Note: Need to aware of caching. May be we need to implement any marker so that there will not arise any race condition in cache_

### Implementation Notes
- I'm implementing REST API endpoint similar to `eth/api.go` in `pandora`;
- I need to look for block first in cache and then in database (behavior of `geth` client);
- Implement processing response for vanguard (prepare payload);

**Comment by mxmar** [comment]
@atif-konasl Some questions related to this issue:

1. This should be REST API endpoint, not RPC subscription, right?
2. In connection with our call did something change with this: `Pending blocks will be existed into its cache and verified block hashes will be stored in db`?

**Comment by mxmar** [comment]
```
Which means to reuse orchestrator/vanguardchain/client? Not understand this.
```
Nvm, sorry :) I was thinking about `gRPC` and asking about `REST` :D my bad.

**Comment by mxmar** [comment]
@atif-konasl In `orchestrator/rpc/api` there is already `api` package. I would prefer to use this for real `REST` implementation not for `RPC/gRPC` purpose. What do you think?

**Comment by mxmar** [comment]
Last comment is solved by meeting between me and @atif-konasl

**Comment by mxmar** [comment]
@atif-konasl This issue is already ongoing -> https://github.com/lukso-network/lukso-orchestrator/tree/feature/12/confirm_block_hashes 

@blazejkrzak is on it.

**Comment by mxmar** [comment]
@atif-konasl I'm moving to https://github.com/lukso-network/vanguard-consensus-engine/issues/21

**Comment by atif-konasl** [comment]
@mxmar okay
