### ISSUE TITLE
BLS signature verification feature integration in Pandora Execution Engine client

### ISSUE THREAD

**Issue by atif-konasl** [lukso-network/lukso-orchestrator#8]
### Public key retrieval from BLS signature verification feature integration in Catalyst client

Implementation:
- Verify BLS signature using BLS public key;
- `extraData` field should contains `TxRootHash`;
- Vanguard receives `extraData` to sign and signs it by BLS;

Flow:
- `catalyst` provides `extraData` for `Vanguard` client;
- `Vanguard` signs by BLS the `extraData` field;
- `Vanguard` provides signed `extraData` back to the `Pandora`;
- `Pandora` fill `mixHash` (`MixDigest`);

Briefing:
- Signature verification process starts when a broadcasted block comes to it. Catalyst client needs a method which will verify the bls signature from `extraData` field of the broadcasted block;
- After successfully verification the signature, the method will calls the existing method to validate other verification steps for the broadcasted block.

**Comment by atif-konasl** [comment]
@mxmar We will implement our features based on catalyst client with branch name - `catalyst-for-executable-beacon-chain` and commit id-`3ded09cd6ba2ac286f42ce05e7ffcc19c7f1fb8b`

**Comment by mxmar** [comment]
PR: https://github.com/silesiacoin/catalyst/pull/1

**Comment by mxmar** [comment]
Module prepared: https://github.com/silesiacoin/bls

**Comment by blazejkrzak** [comment]
Module was prepared, I close this issue
